Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 71, in serve
    await self._serve(sockets)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 78, in _serve
    config.load()
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cwoh\Desktop\01. Project\03. Platform\3. Test\backend\app\main.py", line 8, in <module>
    from app.config import settings
  File "C:\Users\cwoh\Desktop\01. Project\03. Platform\3. Test\backend\app\config.py", line 4, in <module>
    from pydantic import BaseSettings, Field, AnyHttpUrl
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\__init__.py", line 426, in __getattr__
    return _getattr_migration(attr_name)
  File "C:\Users\cwoh\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.11/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.11/u/import-error
